name: 🚀 Deploy website on push

on:   
  push:
    branches:
      - master
      
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Use Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
        
    - name: 🔨 Build Project
      run: |
        npm ci
        npm run build
    
    - name: 📂 Sync files
      uses: milanmk/actions-file-deployer@master
      with:
        remote-protocol: "ftp"
        remote-host: "ftp.oyfaatuva.com"
        remote-user: ${{ secrets.CPANEL_FTP_USERNAME }}
        remote-password: ${{ secrets.CPANEL_FTP_PASSWORD }}
        local-path: ./dist/
        remote-path: /public_html
